window.HCC_DISHES = [
  { id: "locro", cat: "soup", price: 6, img: "img/locro.jpg",
    name: { en: "Potato & cheese locro", es: "Locro de papa" },
    desc: { en: "Creamy highland potatoes, milk, and queso fresco, finished with avocado and a little ají.", es: "Papas de altura, leche y queso fresco, con aguacate y un poco de ají." } },
  { id: "quinoa-soup", cat: "soup", price: 6, img: "img/quinoa.jpg",
    name: { en: "Quinoa cream soup", es: "Crema de quinoa" },
    desc: { en: "A quiet, nourishing bowl — quinoa simmered with vegetables and a touch of cream.", es: "Un tazón quieto y nutritivo — quinoa con verduras y un toque de crema." } },
  { id: "garden-salad", cat: "salad", price: 5, img: "img/salad.jpg",
    name: { en: "Garden salad", es: "Ensalada de la huerta" },
    desc: { en: "Greens, roasted beet, orange, red onion, and toasted seeds with a light citrus dressing.", es: "Hojas, betarraga asada, naranja, cebolla morada y semillas tostadas, con aderezo cítrico." } },
  { id: "seco", cat: "entree", price: 11, img: "img/seco.jpg",
    name: { en: "Cilantro chicken", es: "Seco de pollo" },
    desc: { en: "Slow-stewed chicken in a golden cilantro sauce, with yellow rice and ripe plantain.", es: "Pollo guisado en salsa dorada de cilantro, con arroz amarillo y maduro." } },
  { id: "trout", cat: "entree", price: 12, img: "img/trout.jpg",
    name: { en: "Baked trout", es: "Trucha al horno" },
    desc: { en: "Andean trout with herbs, two llapingachos, peanut sauce, and a sharp cabbage slaw.", es: "Trucha andina con hierbas, dos llapingachos, salsa de maní y ensalada de col." } },
  { id: "carne", cat: "entree", price: 12, img: "img/carne.jpg",
    name: { en: "Achiote beef", es: "Carne colorada" },
    desc: { en: "Cuenca-style beef simmered with achiote and spices, served with mote and pickled onion.", es: "Carne al estilo de Cuenca, con achiote y especias, mote y cebolla encurtida." } },
  { id: "llapingachos", cat: "side", price: 5, img: "img/sides.jpg",
    name: { en: "Llapingachos", es: "Llapingachos" },
    desc: { en: "Pan-fried potato patties stuffed with cheese, with salsa de maní.", es: "Tortillas de papa rellenas de queso, con salsa de maní." } },
  { id: "maduros", cat: "side", price: 4, img: "img/sides.jpg",
    name: { en: "Ripe plantains", es: "Maduros" },
    desc: { en: "Slow-fried sweet plantain — the side everyone finishes first.", es: "Plátano maduro frito despacio — el acompañamiento que se acaba primero." } },
  { id: "mote", cat: "side", price: 4, img: "img/sides.jpg",
    name: { en: "Mote", es: "Mote" },
    desc: { en: "Hominy, simply seasoned — the highland staple.", es: "Mote sazonado con sencillez — el básico de la sierra." } },
  { id: "flan", cat: "dessert", price: 5, img: "img/flan.jpg",
    name: { en: "Caramel flan", es: "Flan de vainilla" },
    desc: { en: "A quiet vanilla custard with a dark caramel coat.", es: "Flan de vainilla con capa de caramelo oscuro." } },
  { id: "compote", cat: "dessert", price: 4, img: "img/flan.jpg",
    name: { en: "Fruit compote", es: "Compota de frutas" },
    desc: { en: "Seasonal fruit, gently stewed — good warm or cold.", es: "Fruta de temporada, cocida con calma — buena caliente o fría." } }
];
